version: "3.9"

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./infra
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_RETENTION_HOURS: 168
    ports:
      - "9092:9092"

  service:
    build:
      context: ../.
    container_name: service
    depends_on:
      - redis
      - kafka
    environment:
      REDIS_ADDRESS: redis:6379
      KAFKA_BROKER_ADDRESS: kafka:9092
    ports:
      - "8080:8080"
    command: ["./main"]
